services:
  - type: web
    name: employee-management-api
    env: docker
    region: singapore
    plan: free
    rootDir: employee-management-api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: APP_BASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: /tmp/uploads/photos
      - key: UPLOAD_DIR_DOCS
        value: /tmp/uploads/documents
      - key: UPLOAD_DIR_COMPANY
        value: /tmp/uploads/company
      - key: LOG_LEVEL
        value: INFO
