export interface PendingRegistration {
  id: number;
  registrationCode: string;
  firstName: string;
  middleName?: string;
  surname: string;
  mobile: string;
  email?: string;
  dob?: string;
  gender?: string;
  prefix?: string;
  maritalStatus?: string;
  presentAddress?: string;
  permanentAddress?: string;
  aadharNumber?: string;
  panNumber?: string;
  highestQualification?: string;
  designation?: string;
  doj?: string;
  bankName?: string;
  accountNumber?: string;
  ifscCode?: string;
  branch?: string;
  fatherName?: string;
  fatherPhone?: string;
  photoUrl?: string;
  aadharDocUrl?: string;
  panDocUrl?: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  rejectionReason?: string;
  createdAt?: string;
  approvedAt?: string;
  approvedBy?: string;
  languages?: string;
}
